### ISSUE TITLE
Windows 10: 'git clone' - Error: invalid path 'VSCode/Part3/NorthwindWeb/..\Northwind.db'

### ISSUE THREAD

**Issue by mihsta** [markjprice/cs7dotnetcore2#11]
Error while git cloning to local repo.

Problem with file name '..\Northwind.db'

Workaround: rename '..\Northwind.db' to 'Northwind.db'

![Git_clone_error_W10](https://user-images.githubusercontent.com/2338881/83418814-d9ee2280-a42c-11ea-98ae-287d9758fd83.png)

**Comment by markjprice** [comment]
Thanks. I've deleted that file.
