### ISSUE TITLE
GetStreamAsync().Result hangs UI thread.

### ISSUE THREAD

**Issue by myfero** [markjprice/cs7dotnetcore2#5]
Hi Mark,

I believe code in CategoriesViewModel that asks for service response is very bad example and shouldn't be shown as such. Generally we shouldn't await in UI thread. UI should be responsive.
From my perspective this example works only because HTTP response is from localhost, not remote server. Just add Thread.Sleep(5000) and see app hang for 5 seconds. 

There are many articles on the internet treating this as potential UI deadlock situation, example:
https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f
For me it was only long await time, not a deadlock but still.

I believe the right solution is to firstly create empty ObservableCollection. Then, create simple task (important it's worker, not UI thread) and run code that's in constructor. No awaits. When request is completed fill Categories collection (still in task) using `CoreApplication.MainView.Dispatcher.RunAsync` to access it via UI thread. 
Since it is ObservableCollection once task is finished collection will be updated automatically.

Hope it helps,
Myfero

**Comment by markjprice** [comment]
Thanks, I have removed this poor example in the fifth edition onwards.
